sudo: false
cache: apt
language: cpp

os:
  - linux
  - osx

env:
#  - BUILD_TYPE=Debug
  - BUILD_TYPE=Release

addons:
  apt:
    packages:
      - libboost-all-dev
      - python-dev
      - libode-dev
      - libeigen3-dev

install:
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then
      brew install boost-python ode eigen;
    fi

script:
  # Create build directory
  - mkdir build
  - cd build

  # Configure
  - cmake -DCMAKE_BUILD_TYPE=$BUILD_TYPE -DOMPL_LOCAL_PYPLUSPLUS_INSTALL=ON -DOMPL_REGISTRATION=OFF -DCMAKE_INSTALL_PREFIX=tmp ..

  # Skip Python bindings on OS X, since brew doesn't have a compiler that can compile gccxml.
  # On Linux, we need to make sure cmake finds the locally installed gccxml
  # and not the one in /usr/bin
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then
      make installpyplusplus;
      rm CMakeCache.txt;
      cmake -DCMAKE_BUILD_TYPE=$BUILD_TYPE -DOMPL_LOCAL_PYPLUSPLUS_INSTALL=ON -DOMPL_REGISTRATION=OFF -DCMAKE_INSTALL_PREFIX=tmp -DGCCXML=pyplusplus/bin/gccxml ..;
      make -j2 update_bindings;
    fi

  # Build
  - make -j4

  # Run unit tests
  # On OS X, exclude test_machine_specs; fails due to "lazy" memory freeing in Release mode (test passes in Debug builds).
  # On OS X, exclude test_random; fails due to bug in Boost.Random in 1.56.
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then
      ctest -E test_(machine_specs|random)
    else
      ctest
    fi
