language: cpp

matrix:
  include:
    - os: linux
      dist: trusty
      sudo: required
      compiler: gcc
      env: PYTHONPATH=/usr/local/lib/python2.7/dist-packages PATH=${PATH}:${HOME}/castxml/bin JOBS=4
      addons:
        apt:
          packages:
            - libboost1.55-all-dev
            - python-dev
            - libode-dev
            - libeigen3-dev
            - python-pip
      cache:
        apt: true
        directories:
          - ${HOME}/castxml
          - /usr/local
    - os: osx
      osx_image: xcode9.1
      compiler: clang
      env: JOBS=2 PYTHON_EXEC=/usr/local/bin/python3 PYTHON_VERSION=3 CASTXMLCFLAGS="-D__LITTLE_ENDIAN__=1"
      cache:
        directories:
          - /usr/local
    - os: linux
      sudo: required
      services:
        - docker
      env: DOCKERFILE="debian-jessie" JOBS=4
    - os: linux
      sudo: required
      services:
        - docker
      env: DOCKERFILE="ubuntu-xenial" JOBS=4

install:
  - if [ -n "$DOCKERFILE" ]; then
      docker build -t "$DOCKERFILE" -f "scripts/docker/$DOCKERFILE" .;
    fi
  - if [ -z "$DOCKERFILE" -a "$TRAVIS_OS_NAME" = "osx" ]; then
      brew update;
      brew install boost-python --with-python3;
      brew install ode eigen castxml pypy3;
    fi
  - if [ -z "$DOCKERFILE" -a "$TRAVIS_OS_NAME" = "linux" ]; then
      sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test;
      sudo apt-get -y update;
      sudo apt-get -y install g++-5;
      export CXX=g++-5;
      wget -O - https://midas3.kitware.com/midas/download/item/318227/castxml-linux.tar.gz | tar zxf - -C ${HOME};
    fi
  - if [ -z "$DOCKERFILE" ]; then
      sudo -H pip${PYTHON_VERSION} -v install pygccxml pyplusplus;
    fi


script:
  - if [ -n "$DOCKERFILE" ]; then
      docker run "$DOCKERFILE"  /bin/sh -c "mkdir /root/ompl/build && cd /root/ompl/build && cmake -DOMPL_REGISTRATION=OFF -DCMAKE_INSTALL_PREFIX=tmp .. && make -j $JOBS && ctest -j $JOBS";
    else
      mkdir -p build &&
      cd build &&
      cmake -DOMPL_REGISTRATION=OFF -DCMAKE_INSTALL_PREFIX=tmp .. &&
      if [ "$TRAVIS_OS_NAME" = "osx" ]; then cat castxml.cfg; make -j4 update_bindings; fi &&
      make -j $JOBS &&
      ctest -j $JOBS;
    fi
