cache:
  apt: true
  directories:
    - /home/travis/castxml
language: cpp

matrix:
  include:
    - os: linux
      dist: trusty
      sudo: required
    - os: osx
      osx_image: xcode7.2
  allow_failures:
    - os: osx

addons:
  apt:
    packages:
      - libboost-all-dev
      - python-dev
      - libode-dev
      - libeigen3-dev
      - python-pip

install:
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then
      brew update;
      brew outdated boost || brew upgrade boost;
      brew install ode eigen python cmake;
      if [ ! -e /home/travis/castxml ]; then
        curl https://midas3.kitware.com/midas/download/item/318762/castxml-macosx.tar.gz | tar zxf -;
      fi;
    else
      if [ ! -e /home/travis/castxml ]; then
        wget -O - https://midas3.kitware.com/midas/download/item/318227/castxml-linux.tar.gz | tar zxf -;
      fi;
    fi
  - sudo -H pip -v install pygccxml https://bitbucket.org/ompl/pyplusplus/get/1.1.tar.gz


script:
  # Create build directory
  - mkdir -p build
  - cd build

  # Configure
  - cmake -DOMPL_REGISTRATION=OFF -DCMAKE_INSTALL_PREFIX=tmp -DXMLGENERATORPATH=/home/travis/castxml/bin/castxml -DXMLGENERATOR=castxml ..
  # debug
  - grep -E '(PY_P|XML)' CMakeCache.txt

  # generate python bindings
  - make -j4 update_bindings

  # Build
  - make -j4

  # Run unit tests
  # On OS X, exclude test_machine_specs; fails due to "lazy" memory freeing in Release mode (test passes in Debug builds).
  # On OS X, exclude test_random; fails due to bug in Boost.Random in 1.56.
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then
      ctest -E 'test_(machine_specs|random)';
    else
      ctest;
    fi
