version: "3"

services:

  app:
    image: omplapp
    environment:
      - OMPL_BROKER_URL=amqp://broker:5672
      - OMPL_BACKEND_URL=rpc://broker:5672
    user: ompl
    # TODO: replace this gunicorn3 / uWSGI
    entrypoint: ["python3", "/usr/share/ompl/webapp/omplweb.py"]
    ports:
      - "5000:5000"
    volumes:
      - benchmark-data:/tmp
    depends_on:
      - broker
      - worker
      - plannerarena

  worker:
    image: omplapp
    environment:
      - OMPL_BROKER_URL=amqp://broker:5672
      - OMPL_BACKEND_URL=rpc://broker:5672
      - PYTHONPATH=/usr/share/ompl/webapp
    user: ompl
    entrypoint: ["celery", "worker", "--app=omplweb.celery", "--queues=omplapp", "--concurrency=4", "--loglevel=INFO"]
    volumes:
      - benchmark-data:/tmp
    depends_on:
      - broker

  plannerarena:
    image: plannerarena
    ports:
      - "8888:8888"
    volumes:
      - benchmark-data:/tmp

  broker:
    hostname: broker
    image: rabbitmq:3
    ports:
      - "5672:5672"

volumes:
  benchmark-data: